parameters:
  - name: includeX86
    type: string
    default: ""
  - name: test
    type: string
    default: ""

steps:
- script: echo $(includeX86)
- script: echo $(test)

- ${{ if eq(parameters.includeX86, 'x86') }}:
    - template: install-dotnet-sdk-32bit.yml
      parameters:
        channel: 2.1
    - template: install-dotnet-sdk-32bit.yml
      parameters:
        channel: 3.0
    - template: install-dotnet-sdk-32bit.yml
      parameters:
        channel: 3.1
    - template: install-dotnet-sdk-32bit.yml
      parameters:
        channel: 5.0
    - template: install-dotnet-sdk-32bit.yml
      parameters:
        sdkVersion: $(dotnetCoreSdkLatestVersion)
