
resources:
  pipelines:
  - pipeline: pierotibou.piero-dd-trace-dotnet # Name of the pipeline resource.
    source: pierotibou.piero-dd-trace-dotnet # The name of the pipeline referenced by this pipeline resource.
    trigger: true # Run when any run of consolidated-pipeline completes

steps:
- bash: echo $(resources.pipeline.pierotibou.piero-dd-trace-dotnet.runID)

- task: UseDotNet@2
  displayName: Use .NET 6.0
  inputs:
    packageType: 'sdk'
    version: '6.0.x'

- bash: |
    cd tracer/tools/PipelineMonitor
    dotnet build

- bash: |
    cd tracer/tools/PipelineMonitor
    dotnet run $(resources.pipeline.consolidated-pipeline.runID)