
resources:
  pipelines:
  - pipeline: pierotibou.piero-dd-trace-dotnet # Name of the pipeline resource.
    source: pierotibou.piero-dd-trace-dotnet # The name of the pipeline referenced by this pipeline resource.
    trigger: true # Run when any run of consolidated-pipeline completes

steps:

- task: UseDotNet@2
  displayName: Use .NET 6.0
  inputs:
    packageType: 'sdk'
    version: '6.0.x'

- bash: |
    cd "$(Build.SourcesDirectory)
    ls
    cd tracer
    ls
    cd tools
    ls
    cd PipelineMonitor

- bash: dotnet build
  displayName: "Build"
  workingDirectory: "$(Build.SourcesDirectory)/tracer/tools/PipelineMonitor"
    

- bash: dotnet run $(resources.pipeline.consolidated-pipeline.runID)
  displayName: "Build"
  workingDirectory: "$(Build.SourcesDirectory)/tracer/tools/PipelineMonitor"