
resources:
  pipelines:
  - pipeline: pierotibou.piero-dd-trace-dotnet # Name of the pipeline resource.
    source: pierotibou.piero-dd-trace-dotnet # The name of the pipeline referenced by this pipeline resource.
    trigger: true # Run when any run of consolidated-pipeline completes

steps:
- bash: echo $(resources.pipeline.pierotibou.piero-dd-trace-dotnet.runID)

- task: UseDotNet@2
  displayName: Use .NET 6.0
  inputs:
    packageType: 'sdk'
    version: '6.0.x'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    workingDirectory: 'tracer/tools/PipelineMonitor'

- task: DotNetCoreCLI@2
  displayName: 'Run monitoring'
  inputs:
    command: run
    workingDirectory: 'tracer/tools/PipelineMonitor'
    arguments: '$(resources.pipeline.consolidated-pipeline.runID)'