name: Auto trigger AAS version bump

on:
  release:
    types: [published]

jobs:
  hastalavista:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger AAS release
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/pierotibou/datadog=aas=extension/dispatches \
          -d '{"inputs": {"is_prerelease":"${{github.event.release.prerelease}}", "version":"${{github.event.release.tag_name}}00" }}'
